CREATE TABLE IF NOT EXISTS kbr_play_list(
    id BIGINT AUTO_INCREMENT,
    user_id BIGINT NULL,
    episode_id BIGINT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at BIGINT NULL DEFAULT 0,
    CONSTRAINT kbr_play_list_pk PRIMARY KEY(id)
);